//go:build ignore

// Fetches https://models.dev/api.json and regenerates agents/models_gen.go.
// Usage: go run agents/script/gen_models.go
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

const defaultURL = "https://models.dev/api.json"

type modelEntry struct {
	ID    string `json:"id"`
	Limit struct {
		Context int `json:"context"`
	} `json:"limit"`
}

type provider struct {
	Models map[string]modelEntry `json:"models"`
}

func main() {
	url := os.Getenv("OPENCODE_MODELS_URL")
	if url == "" {
		url = defaultURL
	}

	resp, err := http.Get(url) //nolint:gosec
	if err != nil {
		fmt.Fprintf(os.Stderr, "fetch %s: %v\n", url, err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read body: %v\n", err)
		os.Exit(1)
	}

	var providers map[string]provider
	if err := json.Unmarshal(body, &providers); err != nil {
		fmt.Fprintf(os.Stderr, "parse JSON: %v\n", err)
		os.Exit(1)
	}

	entries := make(map[string]int)
	for _, p := range providers {
		for _, m := range p.Models {
			if m.ID != "" && m.Limit.Context > 0 {
				entries[m.ID] = m.Limit.Context
			}
		}
	}

	keys := make([]string, 0, len(entries))
	for k := range entries {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteString("// Code generated by script/gen_models.go. DO NOT EDIT.\n")
	sb.WriteString("// To regenerate: go run agents/script/gen_models.go\n")
	sb.WriteString("// Source: https://models.dev/api.json\n")
	sb.WriteString("package agents\n\n")
	sb.WriteString("// ModelContextWindow maps model IDs to their context window size in tokens.\n")
	sb.WriteString("// Used to auto-detect MaxTokens when not explicitly configured.\n")
	sb.WriteString("var ModelContextWindow = map[string]int{\n")
	for _, k := range keys {
		escaped := strings.ReplaceAll(k, `\`, `\\`)
		escaped = strings.ReplaceAll(escaped, `"`, `\"`)
		fmt.Fprintf(&sb, "\t\"%s\": %d,\n", escaped, entries[k])
	}
	sb.WriteString("}\n")

	// resolve output path relative to this file's location
	_, thisFile, _, _ := runtime.Caller(0)
	outPath := filepath.Join(filepath.Dir(thisFile), "..", "models_gen.go")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("wrote %d entries to %s\n", len(keys), outPath)
}
